### PR TITLE
improv: ensure all commands that extend abscommand has company id option

### PR DESCRIPTION
**Pull request by beesaferoot**
### Brief summary of the change made

With this change, all commands that extend `AbstractSharedCommand` propagate `company-id` option. 

Closes: #91 

### Pull Request checklist

Please confirm you have completed any of the necessary steps below.

- [x] Meaningful Pull Request title and description
- [x] Changes tested as described above
- [ ] Added appropriate documentation for the change.
- [ ] Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by dmohns — DISMISSED** [review]
Nice, thanks 👍

**Comment by dmohns** [comment]
@beesaferoot could you check the failing linter?

**Comment by dmohns** [comment]
Btw: Is this also directly resolving https://github.com/EnAccess/micropowermanager/issues/91 ? Or are additional steps required this #91 to resolved?

**Comment by beesaferoot** [comment]
> Btw: Is this also directly resolving #91 ? Or are additional steps required this #91 to resolved?

This directly fixes #91, should have added this to the issue description. Sorry :)

**Pull request merged**
